bootstrap_servers: "boot-jk60kv0x.c2.kafka-serverless.us-east-1.amazonaws.com:9098"

topics:
  - name: demo-orders
    partitions: 3
    replication_factor: 3
    config:
      cleanup.policy: compact
      min.insync.replicas: "2"
      retention.ms: "604800000"  # 7 days

  - name: demo-payments
    partitions: 2
    replication_factor: 3
    config:
      cleanup.policy: delete
      retention.ms: "259200000"  # 3 days
